name: 🐛 Bug Report
description: Report a bug to help us improve the project
title: "[BUG] - <title>"
labels: ["bug", "🆕 Needs triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: "Please fill out this template carefully to help us reproduce and fix the issue."

  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "Describe the bug in detail."
      placeholder: "A clear and concise description of what the bug is."

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: "To Reproduce"
      description: "Steps to reproduce the behavior"
      placeholder: "1. Go to ...\n2. Click on ...\n3. See error"

  - type: textarea
    id: current_behavior
    attributes:
      label: "Current behavior"
      description: "Describe what is happening instead of the expected behavior"
      placeholder: "What actually happens?"

  - type: textarea
    id: expected_behavior
    attributes:
      label: "Expected behavior"
      description: "Describe what you expected to happen"
      placeholder: "What should happen instead?"

  - type: textarea
    id: screenshots
    attributes:
      label: "Screenshots"
      description: "If applicable, add screenshots to help explain your problem"
      placeholder: "Paste screenshot links or attach images"

  - type: input
    id: app_version
    attributes:
      label: "App version"
      description: "Which version of the application are you using?"
      placeholder: "e.g. 1.2.3"

  - type: input
    id: plugins
    attributes:
      label: "Plugins and versions"
      description: "List any plugins or extensions and their versions"
      placeholder: "Plugin X v1.0, Plugin Y v2.3"

  - type: dropdown
    id: device_type
    attributes:
      label: "Device type"
      description: "Select the type of device"
      options:
        - "All"
        - "PC"
        - "Smartphone"
        - "Tablet"

  - type: dropdown
    id: browser
    attributes:
      label: "Browser"
      description: "Select the browser you are using"
      options:
        - "All"
        - "Chrome"
        - "Firefox"
        - "Safari"
        - "Edge"
        - "Other"
